version: 2

sources:
  - name: brz
    schema: bronze
    tables:
      - name: listings
        identifier: raw_listings
        
      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews

  - name: slv
    schema: silver
    tables:
      - name: listings_cleansed
        identifier: listings_cleansed

      - name: hosts_cleansed
        identifier: listings_cleansed
        
      - name: reviews_cleansed
        identifier: listings_cleansed

      - name: full_moon_dates
        identifier: seed_full_moon_dates